# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# users = User.create([
#   { name: 'Adam', email: 'adam@email.com', password: 'pass1', gender: 'Male', age: 20, location: 'Burwood'},
#   { name: 'Ben', email: 'ben@email.com', password: 'pass2', gender: 'Male', age: 30, location: 'St Kilda'},
#   { name: 'Cat', email: 'cat@email.com', password: 'pass3', gender: 'Female', age: 25, location: 'Richmond'},
#   { name: 'Denise', email: 'denise@email.com', password: 'pass4', gender: 'Female', age: 50, location: 'Richmond'},
#   { name: 'Edgar', email: 'edgar@email.com', password: 'pass5', gender: 'Male', age: 45, location: 'Ivanhoe'},
#   ]);
activities = Activity.create([
  { title: 'Walk the Tan', start: '2016-5-19 12:30:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '10' },
  { title: 'Bowling with Roman', start: '2016-3-29 16:30:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '10' },
  { title: 'Table Tennis', start: '2016-4-10 10:00:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '4' },
  { title: 'Snorkelling', start: '2016-8-30 07:45:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '9' },
  { title: 'Walk the dog', start: '2016-6-23 18:00:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '9' },
  { title: 'Golf at Burnley', start: '2016-3-09 11:15:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '7' },
  { title: 'Geocaching', start: '2016-11-25 20:20:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '1' },
  { title: 'A picnic', start: '2016-7-15 09:50:00', description: 'Lorem Khaled Ipsum is a major key to success. Cloth talk. Learning is cool, but knowing is better, and I know the key to success. Let’s see what Chef Dee got that they don’t want us to eat. The key to more success is to have a lot of pillows. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. They don’t want us to win. Congratulations, you played yourself.', user_id: '6' },
  ]);
